name: cta
dependencies:
- alabaster=0.7.7=py35_0
- appnope=0.1.0=py35_0
- astropy=1.1.2=np110py35_0
- babel=2.2.0=py35_0
- cycler=0.10.0=py35_0
- cython=0.23.4=py35_1
- decorator=4.0.9=py35_0
- docutils=0.12=py35_0
- freetype=2.5.5=0
- iminuit=1.2=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.1.2=py35_0
- ipython-notebook=4.0.4=py35_0
- ipython-qtconsole=4.0.1=py35_0
- ipython_genutils=0.1.0=py35_0
- jedi=0.9.0=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.4.0=py35_0
- jupyter_client=4.2.1=py35_0
- jupyter_core=4.1.0=py35_0
- libpng=1.6.17=0
- llvmlite=0.9.0=py35_0
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mistune=0.7.1=py35_0
- mkl=11.3.1=0
- nbconvert=4.1.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.1.0=py35_0
- numba=0.24.0=np110py35_0
- numpy=1.11.0=py35_0
- openssl=1.0.2g=0
- path.py=8.1.2=py35_1
- pep8=1.7.0=py35_0
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pip=8.1.1=py35_1
- psutil=4.1.0=py35_0
- ptyprocess=0.5=py35_0
- py=1.4.31=py35_0
- pyflakes=1.1.0=py35_0
- pygments=2.1.1=py35_0
- pyhessio=0.5.4=py3
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_1
- pytest=2.8.5=py35_0
- python=3.5.1=0
- python-dateutil=2.5.0=py35_0
- python.app=1.2=py35_4
- pytz=2016.1=py35_0
- pyzmq=15.2.0=py35_0
- qt=4.8.7=1
- qtconsole=4.1.1=py35_0
- readline=6.2=2
- rope=0.9.4=py35_1
- scikit-learn=0.17.1=np110py35_0
- scipy=0.17.0=np110py35_0
- setuptools=20.7.0=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.3.5=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- spyder=2.3.8=py35_1
- sqlite=3.9.2=0
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.1.0=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - ctapipe (/Users/Jason/Software/ctapipe)==0.0.dev486
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.1
  - jupyter-core==4.1.0
  - pyhessio (/Users/Jason/Software/pyhessio)==0.5.4
  - rope-py3k==0.9.4.post1
  - sphinx-rtd-theme==0.1.9
  - tqdm==4.5.0

